### ISSUE TITLE
GitHub uses automatic redirect to HTTPS

### ISSUE THREAD

**Issue by Kdecherf** [eschnou/storytlr#33]
Storytlr fails when importing Github because they activated automatic redirect to HTTPS version.

How to fix:
Change 'http://' to 'https://' in protected/application/plugins/github/models/GithubModel.php

**Comment by jmhobbs** [comment]
Changed it in plugin source:
https://github.com/jmhobbs/storytlr-plugin-github

And in my branch:
https://github.com/jmhobbs/storytlr

@eschnou - My branch was out of date, but it should merge clean now if you want to pull that in.

**Comment by eschnou** [comment]
@john Thank you for the fix, it is now in storytlr/develop. I had however to cherry pick instead of merging, I think it is because your master branch is the one with your own stuff and the develop is the 'clean' storytlr one. Anyway, should not be a major issue for you to update your dev branch now. Cheers !

**Comment by jmhobbs** [comment]
Yeah, sorry.  I'd totally forgotten how we were working on Storytlr.  I'll sync my dev and make sure to work from there.
