### ISSUE TITLE
Merge all branches

### ISSUE THREAD

**Issue by zedascouves** [eschnou/storytlr#60]
May I suggest that all branches be merged into one? Even the people that forked the project, would you be willing to commit your changes?

And then just make "official" releases by releasing a tar.gz file, when you see fit.

I've recently started using this on my own and I can see there are fixes and updates not on the master branch.

Thanks!

**Comment by eschnou** [comment]
> "updates not on the master branch"

That's because the development branch is the 'dev' branch. The master only contains the released stuff. So if you pick the code from the dev branch, you should have the latest. As for the additional features on my personal branch, they are more 'hacks' than stable code, hence their non released status.

I agree that a new release with all the latest patches is long overdue. I should also reorganize the branches so that master is the development trunk. It's on my (too long) to do list. Maybe one day ...

Thanks for your interest in this project !

**Comment by zedascouves** [comment]
You're welcome!
I guess I should fork the dev branch then.

I worry that the longer it takes to do this, the more branches will appear and a lot of repeating work will be done. Do you have an ETA for this?

If you don't mind me asking, would you be willing to pass the project to a maintainer with more time on he's/she's hands?

**Comment by eschnou** [comment]
As I said, all patches are on the dev branch. If you see something missing, feel free to point me to a git commit id and I'll cherry pick. There are indeed many forks out there which have diverted, but if the owners don't send me a pull request, I won't chase the commits.

Thanks for your offer, I would love to get some help maintaining this project, feel free to fork and send me a pull request. I'll review and merge quickly. There are a few open issues in the tracker, that's a good point to start if you look for things to work on.

**Comment by zedascouves** [comment]
Thanks, I'll do that. I can't guarantee I'll work on all the issues, probably only the ones that also affect me. :-)

**Comment by zedascouves** [comment]
I'd like to ask some questions about the plugins, Where's the best place for that, here (on an new issue) or somewhere else?
